markdown: kramdown
rouge: true
encoding: UTF-8
excerpt_separator: ""
safe: true
permalink: /:year/:month/:title/

name: Steve's Space
tag: satisfying your stevesspace.com needs for over a millenia
url: http://stevesspace.com
github-url: https://github.com/xwipeoutx

top-menu:
  - url: /
    text: Home
  - url: /projects.html
    text: Projects
  - url: /archive.html
    text: Archive
  - url: /about-me.html
    text: About Me